version: "3.12"

services:
  app:
    build: .
    working_dir: /code/
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DEBUG: 1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    restart: on-failure
